hubot:
  build: hubot
  volumes:
  - ./hubot/hubots:/home/hubot/hubots
  - ./hubot/hubot-utils:/usr/local/hubot-utils
  links:
    - redis
    - classifier
  command: run-current-hubot
  ports:
    - "8080:8080"
redis:
  image: redis
classifier:
  build: classifier
  ports:
    - "4567:4567"
  command: ruby classifier.rb